### ISSUE TITLE
Not able to Checkout. Error: Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by NodiumX** [gitcoinco/BulkTransactions#6] opened 2020-06-20 09:01 UTC
While checking out of the cart with selected grants. It showing error Cannot read property 'enable' of undefined. Using formatic for checkout. 

**Describe the bug**
 The bug is not allowing to confirm the checkout and is showing error

**To Reproduce**
 First go and select a Grant, Add to Cart, Checkout, Click Fund items and the error will show. 

**Expected behavior**
 Display Error: Cannot read property 'enable' of undefined

**Screenshots**

![Error](https://user-images.githubusercontent.com/44767223/85197996-9b98a480-b302-11ea-96f8-2efc82dae71a.png)

**Comment by mds1** [comment] 2020-06-22 12:29
@owocki Want to transfer this issue to gitcoinco/web?

I think the issue is coming from this line in the checkout flow. https://github.com/gitcoinco/web/blob/31f9afa52076386e5a01ecb9edc3d2177ee3ba2e/app/assets/v2/js/cart.js#L501

@NodiumX Can you confirm that when connected with Fortmatic, if you click the dropdown arrow next to the Fortmatic logo in the toolbar it looks like the screenshot below? It should show your address and ETH balance as shown.
![image](https://user-images.githubusercontent.com/17163988/85286969-6e560e80-b448-11ea-8380-b4bdb30eedf4.png)

I've tried connecting with Fortmatic and initiating the checkout process and was not able to reproduce this, so my thinking is that your wallet may not connected properly. cc @octavioamu

**Comment by mds1** [comment] 2020-06-22 13:03
Looks this this was also posted at https://github.com/gitcoinco/web/issues/6932, so closing this as a duplicate

**Closed by mds1** 2020-06-22 13:03 UTC
